#!/usr/bin/env python

import argparse
import os
import pathlib
import subprocess

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        "Run a playbook."
    )
    parser.add_argument(
        "-i", "--ip-address", dest="ip_address", required=True
    )
    parser.add_argument(
        "-p",
        "--playbook",
        type=pathlib.Path,
        dest="playbook",
        required=True,
    )

    args = parser.parse_args()
    ip_address = args.ip_address
    playbook = args.playbook

    venv_path = pathlib.Path(os.environ["VIRTUAL_ENV"])
    ansible_playbook_path = venv_path / "bin/ansible-playbook"

    command = [
        ansible_playbook_path,
        "-i",
        f"{ip_address},",
        f"{args.playbook}"
    ]
    subprocess.run(command, check=False)
